const settings = {
  schedule_name: 'default_schedule',
  task_name: 'default_task',
  export_extension: '.py',
  streaming: false,
  recording: false,
  playback: false,
  logging: true,
  remote_control: false,
  random_enabled: false,
  random_mouse_path: false,
  random_mouse_position: false,
  random_mouse_range: 4,
  random_mouse_delay: false,
  random_mouse_max_delay: 0.5,
  random_keyboard_delay: false,
  random_keyboard_max_delay: 0.5,
  record_mouse_movement: false,
  mouse_previous_x: 0,
  mouse_previous_y: 0,
  mouse_current_x: 0,
  mouse_current_y: 0,
}
export default settings
