const settings = {
  schedule_name: "default_schedule",
  task_name: "default_task",
  task_action_list: [],
  export_extension: ".py",
  recording: false,
  playback: false,
  random_enabled: true,
  random_mouse_path: true,
  random_mouse_position: true,
  random_mouse_range: 4,
  random_mouse_delay: true,
  random_mouse_max_delay: 0.5,
  random_keyboard_delay: true,
  random_keyboard_max_delay: 0.5,
  record_mouse_movement: false,
  mouse_previous_x: 0,
  mouse_previous_y: 0,
  mouse_current_x: 0,
  mouse_current_y: 0,
  screen_width: 1920,
  screen_height: 1080,
  screen_x_scale: 0.5,
  screen_y_scale: 0.5,
  screen_fps: 1,
  screen_timer: 10,
  screen_timer_max: 10,
};
export default settings;
